### ISSUE TITLE
About the evaluation data for video style transfer 

### ISSUE THREAD

**Issue by Dimlife** [JarrentWu1031/CCPL#10]
Hi! Thanks for sharing the great work!
Could you please share more on the test video for evaluation or share the public URL link of test video for downloading?
Thanks!

**Comment by JarrentWu1031** [comment]
Thank you for your appreciation! We use video sources from MPI Sintel dataset for most evaluations. Please refer to: 'http://sintel.is.tue.mpg.de/' to download the data if needed. You could also choose your own videos and split them into frames to run the testing code.

**Comment by Dimlife** [comment]
Thanks!
