### ISSUE TITLE
About the metircs of the artistic style transfer.

### ISSUE THREAD

**Issue by diaodeyi** [JarrentWu1031/CCPL#11]
Hi, Thanks for your great work!  Would you please provide the script about the SIFID and LPIPS that mentioned in paper?

**Comment by JarrentWu1031** [comment]
> Hi, Thanks for your great work! Would you please provide the script about the SIFID and LPIPS that mentioned in paper?

Thanks for your appreciation! SinGAN ('https://github.com/tamarott/SinGAN') paper has provided the script for SIFID evaluation. As for LPIPS, you could refer to IQA-pytorch.
