### ISSUE TITLE
unable to download vgg_normalized.pth

### ISSUE THREAD

**Issue by vishalkothari** [JarrentWu1031/CCPL#21]
I get message "File is in owner's thrash" from Google drive.

**Comment by JarrentWu1031** [comment]
Thanks for your remind! Since we use the same pretrained model as AdaIN, you can download vgg_normalized.pth under this link: 'https://github.com/naoto0804/pytorch-AdaIN/releases/download/v0.0.0/vgg_normalised.pth' I have modified the link in README as well. Hope it helps you.
