### ISSUE TITLE
GPU to use

### ISSUE THREAD

**Issue by arrrrr3186** [JarrentWu1031/CCPL#22]
Hi,

I trying to execute train.py, and scripts is asking for GPU parameter,
as I am using Nvidia, so which GPU i should mention.

**Comment by JarrentWu1031** [comment]
> Hi,
> 
> I trying to execute train.py, and scripts is asking for GPU parameter, as I am using Nvidia, so which GPU i should mention.

Maybe you could just specify --gpu 0 as the default setting.
