### ISSUE TITLE
Supplementary file

### ISSUE THREAD

**Issue by LorenzoAgnolucci** [JarrentWu1031/CCPL#6]
Hello, I would like to read the supplementary file of the paper but I can't find it anywhere, could you please help me?

**Comment by JarrentWu1031** [comment]
Hi, I'm glad you're interested in our work. I just temporarily upload the supplemental file of this work. You can find it here: https://drive.google.com/file/d/1uXfWAD67gWTWUMSbeIjIONSFBKKw53BG/view?usp=sharing

**Comment by LorenzoAgnolucci** [comment]
Thank you very much!

**Comment by JarrentWu1031** [comment]
You're welcome!
