### ISSUE TITLE
error for running test.py (it seems that the pretrained sct_iter_160000.pth.tar is wrong for artistic style)

### ISSUE THREAD

**Issue by qinhui99** [JarrentWu1031/CCPL#8]
Hi,

When I try to run the following script:
python test.py --content input/content/lenna.jpg --style input/style/in2.jpg --decoder artistic/decoder_iter_160000.pth.tar --SCT artistic/sct_iter_160000.pth.tar --testing_mode artistic

I got some errors:
  File "test.py", line 128, in <module>
    SCT.load_state_dict(torch.load(args.SCT))
  File "/home/huiqin/anaconda3/envs/torch18/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SCT:
        Unexpected key(s) in state_dict: "cnet.4.weight", "cnet.4.bias", "snet.4.weight", "snet.4.bias".
        size mismatch for cnet.0.weight: copying a param with shape torch.Size([256, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 256, 1, 1]).
        size mismatch for cnet.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for cnet.2.weight: copying a param with shape torch.Size([128, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 128, 1, 1]).
        size mismatch for cnet.2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for snet.0.weight: copying a param with shape torch.Size([256, 512, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 256, 3, 3]).
        size mismatch for snet.0.bias: copying a param with shape torch.Size([256]) from checkpoint, the shape in current model is torch.Size([128]).
        size mismatch for snet.2.weight: copying a param with shape torch.Size([128, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 128, 1, 1]).
        size mismatch for snet.2.bias: copying a param with shape torch.Size([128]) from checkpoint, the shape in current model is torch.Size([32]).
        size mismatch for uncompress.weight: copying a param with shape torch.Size([512, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([256, 32, 1, 1]).
        size mismatch for uncompress.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).

**Comment by JarrentWu1031** [comment]
Please specify --testing_mode to 'art' instead of 'artistic'. I think this would work.

**Comment by qinhui99** [comment]
It works. Thank you.
